name: pyviz
channels:
  - conda-forge
dependencies:
  - flake8
  - jinja2
  - markdown
  - pyviz::nbsite
  - pyviz::nbsmoke
  - pyviz::pyctdev
  - pytest
  - pyyaml
  - requests
  - tornado<6
  - pip: 
    - git+https://github.com/crossnox/m2r@v0.2.7#egg=m2r
